services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost/api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge